sudo: required
services:
  - docker
before_install:
  - docker build -t santoshkona/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true santoshkona/docker-react npm run test -- --coverage
language: generic
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-501401444888"
  bucket_path: "docker-react"
  on:
    branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
